### ISSUE TITLE
How to create an lmdb file

### ISSUE THREAD

**Issue by TnTtoo** [zhu-xlab/FGMAE#2]
pretraining data is not in lmdb format. How can I create an lmdb file? Thank you very much for your help

**Comment by wangyi111** [comment]
Hi @TnTtoo Sorry for the very late reply. Notification of this issue seems to haven't reached me. Regarding the lmdb file creation, we have it in `datasets/SSL4EO/ssl4eo_dataset.py`, you can refer to https://github.com/zhu-xlab/FGMAE/blob/1144e5500dacdc60343192071a064af23c2ee937/src/pretrain_ssl/datasets/SSL4EO/ssl4eo_dataset.py#L183

Thanks for your interest and Hope it helps you.
